Homework2(db)
KornilovMikhail/WeatherApp pull request #2
Opened 2018-12-10 16:41 UTC by KornilovMikhail

2018-12-10 16:45 UTC, KornilovMikhail commented
Данные берутся с сервака (и записываются в бд) при первом заходе в приложении и при обновлении свайпом. Во всех остальных случаях данные берутся из бд.

2018-12-15 10:10 UTC, NailShaykhrazievItis requested changes

2018-12-15 10:10 UTC, NailShaykhrazievItis commented on app/src/main/java/com/github/kornilovmikhail/weatherapp/MainActivity.kt
> +                .map { response ->
Только у тебя это в ui треде уже, сделай мапу сразу после вызова

2018-12-15 10:10 UTC, NailShaykhrazievItis commented on app/src/main/java/com/github/kornilovmikhail/weatherapp/MainActivity.kt
> +                    rv_cities.adapter = CityAdapter(cities)
Создавай каждый раз адаптер не прикольно, лучше иницилизируй выше с пустым листом, и добавь адаптер метод для сета(а еще лучше перепиши на листадаптер, там сабмитлист уже есть, но эт не обязательно)

2018-12-15 10:10 UTC, NailShaykhrazievItis commented on app/src/main/java/com/github/kornilovmikhail/weatherapp/OpenWeatherApi.kt
> +                   @Query("cnt") cnt: Int?): Flowable<ListCities>
Тут лучше б сингл подошел, ибо имититься будет все равно один объект только, это респонс из сети

2018-12-15 10:10 UTC, NailShaykhrazievItis commented on app/src/main/java/com/github/kornilovmikhail/weatherapp/db/repositories/WeatherDBRepository.kt
> +class WeatherDBRepository(private val database: WeatherDatabase) {
Сильное заявление

2018-12-15 10:10 UTC, NailShaykhrazievItis commented on app/src/main/java/com/github/kornilovmikhail/weatherapp/MainActivity.kt
> +        mCompositeDisposable.add(client.loadCities(latitude, longitude, 20)
20 можно в константу вынести

2018-12-25 19:03 UTC, closed without merging